#!/bin/bash

PACKAGE_VERSION=$(jq '.version' --raw-output ./package.json)

echo $PACKAGE_VERSION

echo "Versioning Forticons ruby gem"

cd lib/forticons_gem/
rake version\["$PACKAGE_VERSION"\]

echo "Versioning Forticons rails helper gem"

cd ../forticons_helper/
rake version\["$PACKAGE_VERSION"\]

cd ../../
git add lib/
