name: CI
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.2'
      - run: yarn
      - run: bundle install
      - name: Transforming FontAwesome icons
        run: yarn transform-fa
      - name: Building
        run: yarn build
      - run: cp -r icons lib/build/svg
      - uses: actions/upload-artifact@v3
        with:
          name: octicons-build
          path: ./lib/build

  main:
    name: Main project
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: actions/download-artifact@v3
        with:
          name: octicons-build
          path: ./lib/build
      - run: yarn
      - name: Lint
        run: yarn lint
      - name: Test
        run: yarn test

#  octicons_node:
#    name: 'npm:@primer/octicons'
#    needs: build
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./lib/octicons_node
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
#      - uses: actions/download-artifact@v3
#        with:
#          name: octicons-build
#          path: ./lib/build
#      - run: yarn
#      - name: Building
#        run: yarn build
#      - name: Lint
#        run: yarn lint
#      - name: Test
#        run: yarn test

#  octicons_react:
#    name: 'npm:@primer/octicons-react'
#    needs: build
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./lib/octicons_react
#    steps:
#      - uses: actions/checkout@v3
#      - uses: actions/setup-node@v3
#        with:
#          node-version: 18
#      - uses: actions/download-artifact@v3
#        with:
#          name: octicons-build
#          path: ./lib/build
#      - run: yarn
#      - name: Building
#        run: yarn build
#      - name: Lint
#        run: yarn lint
#      - name: Test
#        run: yarn test

  forticons_gem:
    name: 'gem:forticons'
    needs: build
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib/forticons_gem
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.2
      - uses: actions/download-artifact@v3
        with:
          name: forticons-build
          path: ./lib/forticons_gem/lib/build
      - run: bundle install
      - name: Linting
        run: bundle exec rake lint
      - name: Testing
        run: bundle exec rake test
      - name: Build
        run: bundle exec rake build
      - uses: actions/upload-artifact@master
        with:
          name: forticons-gem
          path: ./lib/forticons_gem/pkg

  forticons_helper:
    name: 'gem:forticons_helper'
    needs: forticons_gem
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./lib/forticons_helper
    steps:
      - uses: actions/checkout@v3
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 2.7
      - uses: actions/download-artifact@v3
        with:
          name: forticons-gem
          path: ./lib/forticons_helper/vendor/cache
      - run: bundle install
      - name: Linting
        run: bundle exec rake lint
      - name: Testing
        run: bundle exec rake test

#  octicons_jekyll:
#    name: 'gem:octicons_jekyll'
#    needs: octicons_gem
#    runs-on: ubuntu-latest
#    defaults:
#      run:
#        working-directory: ./lib/octicons_jekyll
#    steps:
#      - uses: actions/checkout@v3
#      - name: Setup Ruby
#        uses: ruby/setup-ruby@v1
#        with:
#          ruby-version: 2.7
#      - uses: actions/download-artifact@v3
#        with:
#          name: octicons-gem
#          path: ./lib/octicons_jekyll/vendor/cache
#      - run: bundle install
#      - name: Linting
#        run: bundle exec rake lint
#      - name: Testing
#        run: bundle exec rake test
